// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package generic

import (
	"go-vnet/manager/server/api/generic"
)

type ControllerV1 struct{}

func NewV1() generic.IGenericV1 {
	return &ControllerV1{}
}
