// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-vnet/manager/server/internal/dao/internal"
)

// networkDeviceDao is the data access object for the table network_device.
// You can define custom methods on it to extend its functionality as needed.
type networkDeviceDao struct {
	*internal.NetworkDeviceDao
}

var (
	// NetworkDevice is a globally accessible object for table network_device operations.
	NetworkDevice = networkDeviceDao{internal.NewNetworkDeviceDao()}
)

// Add your custom methods and functionality below.
