// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-vnet/manager/server/internal/dao/internal"
)

// networkDao is the data access object for the table network.
// You can define custom methods on it to extend its functionality as needed.
type networkDao struct {
	*internal.NetworkDao
}

var (
	// Network is a globally accessible object for table network operations.
	Network = networkDao{internal.NewNetworkDao()}
)

// Add your custom methods and functionality below.
