// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-vnet/manager/server/internal/dao/internal"
)

// quotaDao is the data access object for the table quota.
// You can define custom methods on it to extend its functionality as needed.
type quotaDao struct {
	*internal.QuotaDao
}

var (
	// Quota is a globally accessible object for table quota operations.
	Quota = quotaDao{internal.NewQuotaDao()}
)

// Add your custom methods and functionality below.
