// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"go-vnet/manager/server/internal/dao/internal"
)

// quotaFlowDao is the data access object for the table quota_flow.
// You can define custom methods on it to extend its functionality as needed.
type quotaFlowDao struct {
	*internal.QuotaFlowDao
}

var (
	// QuotaFlow is a globally accessible object for table quota_flow operations.
	QuotaFlow = quotaFlowDao{internal.NewQuotaFlowDao()}
)

// Add your custom methods and functionality below.
