// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package quota

import (
	"go-vnet/manager/server/api/quota"
)

type ControllerV1 struct{}

func NewV1() quota.IQuotaV1 {
	return &ControllerV1{}
}
