// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package device

import (
	"context"

	"go-vnet/manager/server/api/device/v1"
	"go-vnet/manager/server/internal/service"
)

func (c *ControllerV1) GetDeviceList(ctx context.Context, req *v1.GetDeviceListReq) (res *v1.GetDeviceListRes, err error) {
	list, total, err := service.Device().GetDeviceInfoListPagination(ctx, req.Page, req.PageSize, req.Name)
	if err != nil {
		return
	}
	res = &v1.GetDeviceListRes{
		List:  list,
		Total: total,
	}
	return
}
