// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package device

import (
	"context"

	"go-vnet/manager/server/api/device/v1"
	"go-vnet/manager/server/internal/service"
)

func (c *ControllerV1) GetSubDeviceListByDeviceId(ctx context.Context, req *v1.GetSubDeviceListByDeviceIdReq) (res *v1.GetSubDeviceListByDeviceIdRes, err error) {
	list, err := service.Device().GetSubDeviceListByDeviceId(ctx, req.DeviceId)
	if err != nil {
		return
	}
	res = &v1.GetSubDeviceListByDeviceIdRes{
		List: list,
	}
	return
}
