// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package device

import (
	"context"

	"go-vnet/manager/server/api/device/v1"
	"go-vnet/manager/server/internal/service"
)

func (c *ControllerV1) DeleteSubDevice(ctx context.Context, req *v1.DeleteSubDeviceReq) (res *v1.DeleteSubDeviceRes, err error) {
	err = service.Device().DeleteSubDeviceById(ctx, req.SubDeviceId)
	return
}
