# https://goframe.org/docs/web/server-config-file-template
server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level: "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/go_vnet_webserver"

auth:
  skip_verify_local: true
  allowed_timestamp_diff: 0
  apps:
    - appid: "test"
      secret: "test"
      # 同时修改前端的appid环境变量即可变更
    - appid: "go_v_net_server_manager_ui_default_appid"
      secret: "123456"

vnet:
  servers:
    - name: "quic-01"
      address: "0.0.0.0"
      port: 9800
      type: "quic"
    - name: "tcp-01"
      address: "0.0.0.0"
      port: 9800
      type: "tcp"
  p2p:
    addresses:
      - ip: "0.0.0.0"
        port: 9900
        transport: "tcp"
        version: ""