# 客户端配置文件
link: "eyJzdWJfZGV2aWNlX2lkIjoxLCJrZXkiOiJ0ZXN0In0="
address: "127.0.0.1"
port: 9800
insecure_skip_verify: true
public_key: public_key.pem

p2p:
  enabled: true

# 认证配置
auth:
  type: "simple_password"  # simple_password, rsa
  password: ""

# 其他配置可以根据需要添加