# 客户端配置文件
network_id: "37ed08c1-44f0-427e-94d2-bc537ca33fc2"
address: "127.0.0.1"
port: 9800
insecure_skip_verify: true

p2p:
  enabled: true

# 认证配置
auth:
  type: "simple_password"  # simple_password, rsa
  password: ""

# 其他配置可以根据需要添加