# 客户端配置文件
link: "eyJzdWJfZGV2aWNlX2lkIjoxLCJrZXkiOiJ0ZXN0In0="
#link: "eyJzdWJfZGV2aWNlX2lkIjoyLCJrZXkiOiJ0ZXN0In0="
address: "127.0.0.1"
port: 9800
insecure_skip_verify: true
public_key: public_key.pem
device_mode: "" # p2p_only | proxy_only(only work on both side under this mode) | mixed(default)

debug: false

manager:
  # 可选：HTTPS证书配置
  # cert_file: "path/to/cert.crt"
  # key_file: "path/to/cert.key"
  enabled: true
  listen: "127.0.0.1"
  port: 8001
  allowed_ip:
    - 127.0.0.1

p2p:
  enabled: false