// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package client

import (
	"go-vnet/manager/client/api/client"
)

type ControllerV1 struct{}

func NewV1() client.IClientV1 {
	return &ControllerV1{}
}
